- name: Install base packages
  become: true
  dnf:
    name:
      - curl
      - gparted
      - htop
      - thunderbird
      - tree
      - python3
      - python3-pip
      - python3-virtualenv
      - libreoffice
      - gpg
      - tmux
      - pre-commit
      - util-linux-user
      - openssl
      - neovim
    state: latest

- name: Create ~/.local/bin directory if it does not exist
  file:
    path: "{{ home_dir }}/.local/bin"
    state: directory
    recurse: yes

- name: Clone markdown linter
  vars:
    repo_url: "https://github.com/3mdeb/hooks.git"
    repo_path: "{{ home_dir }}/.config/3mdeb-hooks"
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_path }}"
    clone: yes

- name: Create symlink for markdown.sh script
  vars:
    symlink_src: "{{ home_dir }}/.config/3mdeb-hooks/markdown.sh"
    symlink_dest: "{{ home_dir }}/.local/bin/markdown.sh"
  file:
    src: "{{ symlink_src }}"
    dest: "{{ symlink_dest }}"
    state: link
    force: yes

- name: Check the generation of GPU
  become: true
  shell: |
    if test -d "/sys/kernel/debug/dri/1"
    then
      cat /sys/kernel/debug/dri/1/i915_gpu_info | grep "graphics version" | cut -d ' ' -f 3
    else
      cat /sys/kernel/debug/dri/0/i915_gpu_info | grep "graphics version" | cut -d ' ' -f 3
    fi
  register: gpu_gen
  
- name: Install RPM Fusion GPG keys (for Intel CPUs 7th or older generations)
  become: true
  dnf:
    name:
      - distribution-gpg-keys
    state: present
  when: (gpu_gen.stdout | int) <= 7

- name: Import RPM Fusion free GPG keys (for Intel CPUs 7th or older generations)
  become: true
  rpm_key:
    state: present
    key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}
  when: (gpu_gen.stdout | int) <= 7
  
- name: Import RPM Fusion nonfree GPG keys (for Intel CPUs 7th or older generations)
  become: true
  rpm_key:
    state: present
    key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}
  when: (gpu_gen.stdout | int) <= 7

- name: Install RPM Fusion repositories (for Intel CPUs 7th or older generations)
  become: true
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: (gpu_gen.stdout | int) <= 7

- name: Swap ffmpeg-free with ffmpeg (for Intel CPUs 7th or older generations)
  become: true
  dnf:
    name: ffmpeg
    state: present
    allowerasing: true
    disablerepo: ffmpeg-free
  when: (gpu_gen.stdout | int) <= 7

- name: Install libva-intel-driver (for Intel CPUs 7th or older generations)
  become: true
  dnf:
    name: libva-intel-driver
    state: present
  when: (gpu_gen.stdout | int) <= 7

- name: Install and configure SSH
  hosts: localhost
  become: yes

  tasks:
    - name: Install OpenSSH server and client
      dnf:
        name: openssh
        state: present

    - name: Start and enable SSH service
      systemd:
        name: sshd
        state: started
        enabled: yes
